### ISSUE TITLE
  Can not install

### ISSUE THREAD

**Issue by ztrx** [ApuliaSoftware/product_code_by_category#1]
Odoo

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 79, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named product_code_by_category-8

**Comment by OpenCode** [comment]
"product_code_by_category-8" is not the name of the module. Please, remove module and clone it again. I think there is a problem with path name.
